name: landing_page
description: Landing Page de la Carrera de Computacion  de la Universidad
  Politécnica Salesiana.

publish_to: "none"

version: 1.0.0+100

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.15.4
  csv: ^5.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_remote_config: ^4.3.13
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.9
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^10.6.0
  go_router: ^12.0.0
  hovering: ^1.0.4
  path_provider: ^2.1.2
  platform_detector: ^0.2.0
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/logos/
    - assets/images/perfiles/
    - assets/archivos/
