name: landing_page
description: Landing Page de la Carrera de Computacion  de la Universidad
  Politécnica Salesiana.

publish_to: "none"

version: 1.0.0+100

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  firebase_core: ^2.24.0
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^10.6.0
  go_router: ^12.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/logos/
